### ISSUE TITLE
transferir repo a #chile

### ISSUE THREAD

**Issue by eseceve** [sebaestel/asadojs#4]
Van a mover el repo?

**Comment by tmayr** [comment]
Por ahora nah, que se quede acá imho, de ahi vemos, iniciativa > lindi

**Comment by hectorpalmatellez** [comment]
Igual podríamos y ver la cosa de permisos y ahí hacemos un grupito que administre… o todos.

**Comment by eseceve** [comment]
que se motive @sebaestel para que no sea el único aprobando los PRs

**Comment by sebaestel** [comment]
a quien agrego?

**Comment by hectorpalmatellez** [comment]
A @tmayr o a @halles… o los dos :grimacing:

**Comment by sebaestel** [comment]
Done!

**Comment by tmayr** [comment]
Listo!
